JSON_COMMA = ','
JSON_COLON = ':'
JSON_LEFTBRACKET = '['
JSON_RIGHTBRACKET = ']'
JSON_LEFTBRACE = '{'
JSON_RIGHTBRACE = '}'
JSON_QUOTE = '"'

JSON_DICT_FLAG = 'D'
JSON_TUPLE_FLAG = 'T'
JSON_SET_FLAG = 'S'

JSON_WHITESPACE = [' ', '\t', '\b', '\n', '\r']
JSON_SYNTAX = [JSON_COMMA, JSON_COLON, JSON_LEFTBRACKET, JSON_RIGHTBRACKET,
               JSON_LEFTBRACE, JSON_RIGHTBRACE]

JSON_FLAGS = [JSON_DICT_FLAG, JSON_TUPLE_FLAG, JSON_SET_FLAG]

FALSE_LEN = len('false')
TRUE_LEN = len('true')
NULL_LEN = len('null')