TOML_COMMA = ','
TOML_LEFTBRACKET = '['
TOML_RIGHTBRACKET = ']'
TOML_QUOTE = '"'
TOML_NUMBER_QUOTE = "'"
TOML_DOT = '.'
TOML_EQUALS = '='

TOML_DICT_FLAG = 'D'
TOML_TUPLE_FLAG = 'T'
TOML_SET_FLAG = 'S'
TOML_LIST_FLAG = 'L'
TOML_OBJECT_FLAG = 'O'

TOML_WHITESPACE = [' ', '\t', '\n', '\r', '\b']
TOML_SYNTAX = [TOML_COMMA, TOML_LEFTBRACKET, 
                TOML_RIGHTBRACKET, TOML_RIGHTBRACKET, TOML_DOT, TOML_EQUALS, TOML_NUMBER_QUOTE]

TOML_FLAGS = [TOML_DICT_FLAG, TOML_TUPLE_FLAG, TOML_SET_FLAG, TOML_LIST_FLAG, TOML_OBJECT_FLAG]

FALSE_LEN = len('false')
TRUE_LEN = len('true')
NULL_LEN = len('null')