YAML_COLON = ':'
YAML_QUOTE = '"'
YAML_DASH = '-'
YAML_NEWLINE = '\n'

YAML_WHITESPACE = [' ']

FALSE_LEN = len('false')
TRUE_LEN = len('true')
NULL_LEN = len('null')

YAML_SYNTAX = [YAML_COLON, YAML_QUOTE, YAML_DASH, YAML_NEWLINE]

YAML_DICT_FLAG = 'D'
YAML_TUPLE_FLAG = 'T'
YAML_SET_FLAG = 'S'

YAML_FLAGS = [YAML_DICT_FLAG, YAML_TUPLE_FLAG, YAML_SET_FLAG]